spring.application.name=Notification-Alerts

#mysql
spring.datasource.url= jdbc:mysql://localhost:3306/notification_alert
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#mysql dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

kafka.topic.name=trade-execution-alerts

#Kafka Config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=alert-group

#consumer config
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer= org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages= "*"
spring.kafka.consumer.properties.spring.json.value.default.type=com.apex.trade.Notification_Alerts.trade_execution_alerts.dto.TradeEventDTO

#producer config
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#mail configs
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=your-email@gmail.com
#spring.mail.password=your-app-password
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


# MailHog SMTP config
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
